config/routes.rb
RailsCV::Application.routes.draw do
  resources :cvs do
    resources :sections, controller: "cv_sections"
  end

end

app/models/cv.rb
class Cv < ActiveRecord::Base
  has_many :cv_sections
end

app/models/cv_section.rb
class CvSection < ActiveRecord::Base
  belongs_to :cv
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cv_sections_controller.rb
class CvSectionsController < ApplicationController

  before_filter :get_cv

  # GET /cv_sections
  # GET /cv_sections.json
  def index
    @cv_sections = CvSection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cv_sections }
    end
  end

  # GET /cv_sections/1
  # GET /cv_sections/1.json
  def show
    @cv_section = CvSection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cv_section }
    end
  end

  # GET /cv_sections/new
  # GET /cv_sections/new.json
  def new
    @cv_section = CvSection.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cv_section }
    end
  end

  # GET /cv_sections/1/edit
  def edit
    @cv_section = CvSection.find(params[:id])
  end

  # POST /cv_sections
  # POST /cv_sections.json
  def create
    @cv_section = @cv.cv_sections.build(params[:cv_section])

    respond_to do |format|
      if @cv_section.save
        format.html { redirect_to cv_section_path(@cv, @cv_section), notice: 'Cv section was successfully created.' }
        format.json { render json: @cv_section, status: :created, location: @cv_section }
      else
        format.html { render action: "new" }
        format.json { render json: @cv_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cv_sections/1
  # PUT /cv_sections/1.json
  def update
    @cv_section = CvSection.find(params[:id])

    respond_to do |format|
      if @cv_section.update_attributes(params[:cv_section])
        format.html { redirect_to @cv_section, notice: 'Cv section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cv_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cv_sections/1
  # DELETE /cv_sections/1.json
  def destroy
    @cv_section = CvSection.find(params[:id])
    @cv_section.destroy

    respond_to do |format|
      format.html { redirect_to cv_sections_url }
      format.json { head :no_content }
    end
  end

  def get_cv
    @cv = Cv.find(params[:cv_id])
  end
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  # GET /cvs
  # GET /cvs.json
  def index
    @cvs = Cv.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cvs }
    end
  end

  # GET /cvs/1
  # GET /cvs/1.json
  def show
    @cv = Cv.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cv }
    end
  end

  # GET /cvs/new
  # GET /cvs/new.json
  def new
    @cv = Cv.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cv }
    end
  end

  # GET /cvs/1/edit
  def edit
    @cv = Cv.find(params[:id])
  end

  # POST /cvs
  # POST /cvs.json
  def create
    @cv = Cv.new(params[:cv])

    respond_to do |format|
      if @cv.save
        format.html { redirect_to @cv, notice: 'Cv was successfully created.' }
        format.json { render json: @cv, status: :created, location: @cv }
      else
        format.html { render action: "new" }
        format.json { render json: @cv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cvs/1
  # PUT /cvs/1.json
  def update
    @cv = Cv.find(params[:id])

    respond_to do |format|
      if @cv.update_attributes(params[:cv])
        format.html { redirect_to @cv, notice: 'Cv was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cvs/1
  # DELETE /cvs/1.json
  def destroy
    @cv = Cv.find(params[:id])
    @cv.destroy

    respond_to do |format|
      format.html { redirect_to cvs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cv_sections_helper.rb
module CvSectionsHelper
end

app/helpers/cvs_helper.rb
module CvsHelper
end

app/views/cv_sections/_form.html.haml
- if @cv_section.errors.any?
  #error_explanation
    %h2= "#{pluralize(@cv_section.errors.count, "error")} prohibited this cv_section from being saved:"
    %ul
      - @cv_section.errors.full_messages.each do |msg|
        %li= msg

.field
  = f.label :title
  = f.text_field :title
.field
  %p= f.label :content
  = f.text_area :content
.actions
  = f.submit 'Save'

app/views/cv_sections/edit.html.haml
%h1 Editing CV Section in #{@cv.title}.

= form_for @cv_section, url: cv_sections_path(@cv) do |f|
  = render 'form' f:f

= link_to 'Show', @cv_section
\|
= link_to 'Back', cv_sections_path

app/views/cv_sections/index.html.haml
%h1 Listing CV Sections

%table
  %tr
    %th Title
    %th Content
    %th
    %th
    %th

  - @cv_sections.each do |cv_section|
    %tr
      %td= cv_section.title
      %td= truncate cv_section.content, length: 140
      %td= link_to 'Show', cv_section
      %td= link_to 'Edit', edit_cv_section_path(cv_section)
      %td= link_to 'Destroy', cv_section, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cv section', new_cv_section_path

app/views/cv_sections/new.html.haml
%h1 Adding new CV Section to #{@cv.title}.

= form_for @cv_section, url: cv_sections_path(@cv) do |f|
  = render 'form', f:f

= link_to 'Back', cv_sections_path

app/views/cv_sections/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @cv_section.title
%p
  %b Content:
  = @cv_section.content

= link_to 'Edit', edit_cv_section_path(@cv_section)
\|
= link_to 'Back', cv_sections_path

app/views/cvs/_form.html.haml
= form_for @cv do |f|
  - if @cv.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cv.errors.count, "error")} prohibited this cv from being saved:"
      %ul
        - @cv.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_area :address
  .actions
    = f.submit 'Save'

app/views/cvs/edit.html.haml
%h1 Editing cv

= render 'form'

= link_to 'Show', @cv
\|
= link_to 'Back', cvs_path

app/views/cvs/index.html.haml
%h1 Listing cvs

%table
  %tr
    %th Title
    %th Name
    %th Address
    %th
    %th
    %th

  - @cvs.each do |cv|
    %tr
      %td= cv.title
      %td= cv.name
      %td= cv.address
      %td= link_to 'Show', cv
      %td= link_to 'Edit', edit_cv_path(cv)
      %td= link_to 'Destroy', cv, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cv', new_cv_path

app/views/cvs/new.html.haml
%h1 New cv

= render 'form'

= link_to 'Back', cvs_path

app/views/cvs/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @cv.title
%p
  %b Name:
  = @cv.name
%p
  %b Address:
  = @cv.address

%h3 Sections

-@cv.cv_sections.each do |section|
  =section.title

%p=link_to "Add Section", new_cv_section_path(@cv)

%h3 Options

= link_to 'Edit', edit_cv_path(@cv)
\|
= link_to 'Back', cvs_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RailsCV
    =stylesheet_link_tag    "application", media: "all"
    =javascript_include_tag "application"
    =csrf_meta_tags
  %body
    =yield